import type { Category } from "../types";

export const categories: Category[] = [
  { value: "text", label: "Text Tools", icon: "📝", subcategories: ["analysis", "transform", "encoding", "formatting"],
    description: "Analyze, transform, and format text instantly. Count words and characters, convert between cases, compare documents, sort and deduplicate lines, extract emails and URLs, and encode or decode text in various formats. Every tool runs in your browser — your text never leaves your device." },
  { value: "developer", label: "Developer Tools", icon: "💻", subcategories: ["formatters", "converters", "generators", "validators"],
    description: "Essential utilities for web developers and programmers. Format and minify JSON, CSS, JavaScript, and SQL. Convert between data formats like CSV, XML, YAML, and JSON. Generate meta tags, regex patterns, and code boilerplate. Validate and debug JWTs, cron expressions, and user agents." },
  { value: "math", label: "Math Tools", icon: "🔢", subcategories: ["calculators", "statistics", "geometry"],
    description: "Calculators and solvers for everyday math, statistics, and geometry. From basic percentages and averages to standard deviation, matrix operations, and quadratic equations. Also includes practical calculators for BMI, tips, discounts, GPA, and loan payments." },
  { value: "converter", label: "Converters", icon: "🔄", subcategories: ["length", "weight", "volume", "temperature", "data", "speed", "area", "energy"],
    description: "Convert between units of measurement, color formats, number bases, timestamps, timezones, currencies, and data formats. Covers length, weight, volume, temperature, speed, area, energy, and cooking measurements. Accurate conversions with instant results." },
  { value: "generator", label: "Generators", icon: "⚡", subcategories: ["security", "design", "content", "code"],
    description: "Generate passwords, UUIDs, Lorem Ipsum text, color palettes, QR codes, barcodes, and more. Tools for creating secure random data, design assets, placeholder content, and code snippets — all generated instantly in your browser." },
  { value: "image", label: "Image Tools", icon: "🖼️", subcategories: ["resize", "convert", "optimize", "create"],
    description: "Resize, crop, compress, convert, and edit images without uploading to any server. Supports PNG, JPG, WebP, SVG, and GIF formats. Generate favicons, extract color palettes, add watermarks, remove backgrounds, and create memes — all processed locally in your browser for complete privacy." },
  { value: "crypto", label: "Crypto & Security", icon: "🔐", subcategories: ["hashing", "encryption", "analysis", "network"],
    description: "Cryptography and network security tools for developers and IT professionals. Generate MD5, SHA-256, and bcrypt hashes. Encrypt and decrypt data with AES. Check SSL certificates, look up DNS records, query WHOIS data, and analyze password strength. All operations run client-side for security." },
  { value: "seo", label: "SEO & Marketing", icon: "📈", subcategories: ["preview", "analysis", "tracking"],
    description: "Optimize your website for search engines and social media. Preview Open Graph cards, check meta tag lengths, analyze keyword density, build UTM tracking links, generate structured data markup, and test page speed. Ensure your pages look great in Google results and social shares." },
  { value: "utility", label: "Utilities", icon: "🧰", subcategories: ["timers", "productivity", "system"],
    description: "Everyday productivity tools — Pomodoro timers, stopwatches, countdowns, a digital notepad, text-to-speech, keyboard tester, speed test, and more. Simple, focused tools that help you stay organized and get things done." },
  { value: "finance", label: "Finance Tools", icon: "💰", subcategories: ["loans", "investment", "tax", "business", "crypto"],
    description: "Financial calculators for personal and business decisions. Calculate mortgage payments, compound interest, ROI, retirement savings, tax estimates, salary conversions, debt payoff timelines, and break-even points. Make informed money decisions with accurate, instant calculations." },
  { value: "health", label: "Health & Fitness", icon: "❤️", subcategories: ["body", "nutrition", "exercise", "medical"],
    description: "Health and fitness calculators for body metrics, nutrition, and exercise planning. Calculate BMI, body fat percentage, daily calorie needs, macronutrient ratios, heart rate zones, and pace conversions. Track your fitness goals with accurate, science-based calculations." },
  { value: "datetime", label: "Date & Time", icon: "📅", subcategories: ["calculators", "converters", "countdowns"],
    description: "Calculate the difference between dates, convert between timezones, count business days, find what day of the week a date falls on, and create countdowns to important events. Precise date arithmetic for planning and scheduling." },
  { value: "social", label: "Social Media", icon: "📱", subcategories: ["text", "images", "analytics", "content"],
    description: "Tools for growing your social media presence. Generate trending hashtags, resize images for every platform, create engaging bios and captions, calculate engagement rates, format threads, and download YouTube thumbnails. Optimized for Instagram, X, LinkedIn, TikTok, and YouTube." },
  { value: "pdf", label: "PDF Tools", icon: "📄", subcategories: ["convert", "edit", "merge"],
    description: "Work with PDF files directly in your browser. Convert documents to and from PDF, merge multiple PDFs, split pages, compress file size, and extract text. All processing happens locally — your files never leave your device." },
  { value: "education", label: "Education", icon: "🎓", subcategories: ["math", "science", "language", "grades"],
    description: "Study tools for students and educators. Calculate grades, generate citations in MLA/APA/Chicago formats, create flashcards, explore the periodic table, practice multiplication, test typing speed, and solve equations. Everything you need to study smarter." },
  { value: "writing", label: "Writing Tools", icon: "✍️", subcategories: ["analysis", "generation", "formatting"],
    description: "Sharpen your writing with tools that analyze readability, detect passive voice, find cliches, check grammar, generate headlines, and create content outlines. Perfect for bloggers, copywriters, students, and anyone who wants to communicate more clearly." },
  { value: "business", label: "Business Tools", icon: "💼", subcategories: ["documents", "calculators", "planning"],
    description: "Tools for business planning and operations. Generate invoices, check domain availability, calculate margins and markups, create business name ideas, plan budgets, and estimate pricing. Essential utilities for entrepreneurs and small business owners." },
  { value: "gaming", label: "Gaming & Fun", icon: "🎮", subcategories: ["random", "generators", "tools"],
    description: "Random generators, dice rollers, coin flippers, name generators, and other fun tools for gaming, tabletop RPGs, and entertainment. Fair, cryptographically random results for when the stakes are high — or just for fun." },
];
