import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "ToolboxHub terms of service — rules and guidelines for using our free online tools.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
      <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
        Terms of Service
      </h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Last updated: March 21, 2026
      </p>

      <div className="mt-8 space-y-8 text-sm leading-relaxed text-muted-foreground">
        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing or using ToolboxHub (
            <Link
              href="https://toolboxhub.net"
              className="text-primary hover:underline"
            >
              toolboxhub.net
            </Link>
            ), you agree to be bound by these Terms of Service
            (&ldquo;Terms&rdquo;). If you do not agree, please do not use the
            Site.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">
            2. Description of Service
          </h2>
          <p>
            ToolboxHub provides a collection of free, browser-based utility
            tools including text processors, converters, calculators, generators,
            and more. All tools run client-side in your browser — your data is
            not uploaded to or processed on our servers.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">
            3. Use of the Service
          </h2>
          <p>You agree to use ToolboxHub only for lawful purposes. You may not:</p>
          <ul className="mt-2 list-disc pl-5 space-y-1">
            <li>
              Use the Site in any way that violates applicable laws or
              regulations
            </li>
            <li>
              Attempt to interfere with, compromise, or disrupt the Site or its
              infrastructure
            </li>
            <li>
              Use automated scripts or bots to access the Site in a manner that
              degrades performance for other users
            </li>
            <li>
              Reproduce, duplicate, or resell any part of the Site without
              express written permission
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">
            4. Intellectual Property
          </h2>
          <p>
            The ToolboxHub name, logo, design, and original content are the
            property of ToolboxHub. The tools themselves are provided for your
            free, personal, and commercial use. Outputs generated by the tools
            belong to you.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">
            5. Disclaimer of Warranties
          </h2>
          <p>
            ToolboxHub is provided <strong>&ldquo;as is&rdquo;</strong> and{" "}
            <strong>&ldquo;as available&rdquo;</strong> without warranties of
            any kind, either express or implied, including but not limited to
            implied warranties of merchantability, fitness for a particular
            purpose, and non-infringement.
          </p>
          <p className="mt-2">
            We do not guarantee that the tools will produce accurate, complete,
            or error-free results. You are responsible for verifying any outputs
            before relying on them for important decisions, especially for
            financial, health, or legal matters.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">
            6. Limitation of Liability
          </h2>
          <p>
            To the fullest extent permitted by law, ToolboxHub and its
            operators shall not be liable for any indirect, incidental, special,
            consequential, or punitive damages, or any loss of profits or
            revenue, whether incurred directly or indirectly, arising from your
            use of the Site or any tool on the Site.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">
            7. Third-Party Services
          </h2>
          <p>
            The Site may display advertisements served by third-party ad
            networks (e.g., Google AdSense). These third parties may collect
            information about your visits as described in our{" "}
            <Link href="/privacy" className="text-primary hover:underline">
              Privacy Policy
            </Link>
            . We are not responsible for the content or practices of third-party
            advertisers.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">
            8. Availability
          </h2>
          <p>
            We strive to keep ToolboxHub available at all times but do not
            guarantee uninterrupted access. The Site may be temporarily
            unavailable due to maintenance, updates, or circumstances beyond our
            control.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">
            9. Changes to Terms
          </h2>
          <p>
            We reserve the right to modify these Terms at any time. Updated
            Terms will be posted on this page with a new &ldquo;Last
            updated&rdquo; date. Your continued use of the Site after any
            changes constitutes acceptance of the new Terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">
            10. Governing Law
          </h2>
          <p>
            These Terms shall be governed by and construed in accordance with
            the laws of the jurisdiction in which ToolboxHub operates, without
            regard to conflict of law provisions.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">
            11. Contact
          </h2>
          <p>
            If you have any questions about these Terms, please reach out via
            the{" "}
            <Link href="/contact" className="text-primary hover:underline">
              Contact page
            </Link>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
